apiVersion: v1
kind: ConfigMap
metadata:
  name: dr-config
  namespace: secureai
data:
  primary-region: eastus
  dr-region: westus
  failover-procedure: |
    1. Verify primary region failure
    2. Switch DNS to DR region
    3. Restore from latest backup
    4. Verify system integrity
    5. Resume operations in DR region
  recovery-time-objective: "4h"
  recovery-point-objective: "15m"
