apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-test-executor
  namespace: secureai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dr-test-executor
  template:
    metadata:
      labels:
        app: dr-test-executor
    spec:
      serviceAccountName: dr-test-executor
      containers:
      - name: executor
        image: secureairegistry.azurecr.io/dr-test-executor:latest
        env:
        - name: SCENARIOS_CONFIG
          value: /etc/dr-test/scenarios.yaml
        volumeMounts:
        - name: scenarios-config
          mountPath: /etc/dr-test
        - name: results
          mountPath: /var/log/dr-test
      volumes:
      - name: scenarios-config
        configMap:
          name: dr-test-scenarios
      - name: results
        persistentVolumeClaim:
          claimName: dr-test-results
