apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-test-executor
  namespace: secureai

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dr-test-executor
  namespace: secureai
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dr-test-executor
  namespace: secureai
subjects:
- kind: ServiceAccount
  name: dr-test-executor
  namespace: secureai
roleRef:
  kind: Role
  name: dr-test-executor
  apiGroup: rbac.authorization.k8s.io
