apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-validation-tests
  namespace: secureai
data:
  additional-tests.yaml: |
    tests:
      - name: "incremental-backup-validation"
        description: "Validate incremental backup functionality"
        steps:
          - action: "create-test-data"
            size: "1Gi"
            change_rate: "10%"
          - action: "perform-backup"
            type: "incremental"
          - action: "verify-incremental"
            expected_size_range: "90-110MB"
          - action: "verify-deduplication"
            min_ratio: 0.8

      - name: "disaster-recovery-simulation"
        description: "Full DR scenario testing"
        steps:
          - action: "simulate-disaster"
            type: "complete-outage"
          - action: "trigger-failover"
            target: "dr-region"
          - action: "restore-from-backup"
            consistency_check: true
          - action: "verify-applications"
            health_check: true
          - action: "verify-data-integrity"
            sampling_rate: 0.2

      - name: "compliance-validation"
        description: "Validate compliance requirements"
        checks:
          - type: "encryption-at-rest"
            algorithm: "AES-256"
          - type: "data-retention"
            policy: "90-days"
          - type: "audit-trail"
            required_fields: ["timestamp", "user", "action", "resource"]
          - type: "gdpr-compliance"
            checks: ["right-to-erasure", "data-portability"]
