apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-validation-tests
  namespace: secureai
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-validator
          containers:
          - name: validator
            image: secureairegistry.azurecr.io/backup-validator:latest
            env:
            - name: VALIDATION_MODE
              value: "comprehensive"
            - name: BACKUP_LOCATION
              value: "azure-backup"
            - name: TEST_NAMESPACE
              value: "backup-validation"
            volumeMounts:
            - name: validation-config
              mountPath: /etc/backup-validation
            - name: test-results
              mountPath: /var/log/validation
          volumes:
          - name: validation-config
            configMap:
              name: backup-validation-config
          - name: test-results
            persistentVolumeClaim:
              claimName: backup-validation-results
          restartPolicy: OnFailure
