apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: performance-monitor
  namespace: secureai
spec:
  selector:
    matchLabels:
      app: performance-optimizer
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: performance-alerts
  namespace: secureai
spec:
  groups:
  - name: performance.rules
    rules:
    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High API latency detected
        description: 95th percentile latency is above 500ms

    - alert: HighCPUUsage
      expr: |
        container_cpu_usage_seconds_total{namespace="secureai"} > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: Container CPU usage above 85% for 15 minutes

    - alert: HighMemoryUsage
      expr: |
        container_memory_working_set_bytes{namespace="secureai"} / container_spec_memory_limit_bytes{namespace="secureai"} > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Container memory usage above 85% for 15 minutes
