apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: secureai-platform
spec:
  template:
    spec:
      containers:
      - image: gcr.io/secureai-nexus/secureai-platform:latest
        env:
        - name: PORT
          value: "8080"
        - name: DOMAIN
          value: "secureai.eriethio.com"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
