apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureai-platform
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: secureai-platform
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
