apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-verification
  namespace: secureai
spec:
  schedule: "*/30 * * * *"  # Run every 30 minutes
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: verification-executor
          containers:
          - name: verifier
            image: secureairegistry.azurecr.io/deployment-verifier:latest
            securityContext:
              runAsNonRoot: true
              readOnlyRootFilesystem: true
            env:
            - name: TEST_CONFIG
              value: /etc/verification/verification-tests.yaml
            - name: AZURE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: json-credentials
            volumeMounts:
            - name: test-config
              mountPath: /etc/verification
              readOnly: true
            - name: results
              mountPath: /var/verification/results
          volumes:
          - name: test-config
            configMap:
              name: deployment-verification
          - name: results
            persistentVolumeClaim:
              claimName: verification-results
          restartPolicy: OnFailure
