apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureai-platform
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secureai-platform
  template:
    metadata:
      labels:
        app: secureai-platform
    spec:
      containers:
      - name: secureai-platform
        image: gcr.io/secureai-nexus/secureai-platform:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
