apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureai-platform
  namespace: production
spec:
  replicas: {{.Values.replicas}}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: secureai-platform
  template:
    metadata:
      labels:
        app: secureai-platform
    spec:
      serviceAccountName: secureai-service-account
      containers:
      - name: secureai-platform
        image: gcr.io/secureai-nexus/secureai-platform:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: secureai-config
              key: PROJECT_ID
        resources:
          requests:          
            cpu: "{{.Values.cpu.request}}"
            memory: "{{.Values.memory.request}}"
          limits:          
            cpu: "{{.Values.cpu.limit}}"
            memory: "{{.Values.memory.limit}}"

