apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secureai-platform
  namespace: default
spec:
  selector:
    matchLabels:
      app: secureai-platform
  endpoints:
  - port: http
