apiVersion: v1
kind: Service
metadata:
  name: secureai-platform
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: secureai-platform
