apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-metrics-exporter
  namespace: secureai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-metrics
  template:
    metadata:
      labels:
        app: backup-metrics
    spec:
      containers:
      - name: metrics-exporter
        image: secureairegistry.azurecr.io/backup-metrics:latest
        ports:
        - containerPort: 9090
          name: metrics
        env:
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-backup-creds
              key: storage-account
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-backup-creds
              key: storage-key
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 5
