apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-specific-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: secureai-platform
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Pods
    pods:
      metric:
        name: model_request_latency_seconds
      target:
        type: AverageValue
        averageValue: 0.5
  - type: Object
    object:
      metric:
        name: model_request_total
      describedObject:
        apiVersion: v1
        kind: Service
        name: secureai-platform
      target:
        type: Value
        value: 1000 