apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureai-production

resources:
- ../../base

patches:
- path: patches/deployment.yaml

configMapGenerator:
- name: secureai-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - DOMAIN=getaisecured.com
