apiVersion: v1
kind: ConfigMap
metadata:
  name: compliance-documentation
  namespace: secureai
data:
  security-controls.yaml: |
    controls:
      access-control:
        - id: AC-1
          title: "Access Control Policy and Procedures"
          implementation:
            - Azure AD B2C for authentication
            - Role-based access control (RBAC)
            - Multi-factor authentication (MFA)
          evidence:
            - Authentication logs
            - Access control matrices
            - MFA configuration

      data-protection:
        - id: DP-1
          title: "Data Encryption"
          implementation:
            - Azure Key Vault for key management
            - TLS 1.3 for data in transit
            - AES-256 for data at rest
          evidence:
            - Encryption configurations
            - Key rotation logs
            - SSL/TLS certificates

      audit-logging:
        - id: AU-1
          title: "Audit and Accountability"
          implementation:
            - Azure Monitor for logging
            - Prometheus for metrics
            - Grafana for visualization
          evidence:
            - Audit logs
            - Monitoring dashboards
            - Alert configurations

  compliance-matrix.yaml: |
    frameworks:
      gdpr:
        requirements:
          - id: GDPR-1
            title: "Data Protection by Design"
            controls: ["DP-1", "AC-1"]
            status: "Implemented"
            evidence: "Encryption and access controls"

          - id: GDPR-2
            title: "Right to Erasure"
            controls: ["DP-2"]
            status: "Implemented"
            evidence: "Data deletion procedures"

      hipaa:
        requirements:
          - id: HIPAA-1
            title: "Access Controls"
            controls: ["AC-1", "AU-1"]
            status: "Implemented"
            evidence: "Authentication and audit logs"

          - id: HIPAA-2
            title: "Encryption and Decryption"
            controls: ["DP-1"]
            status: "Implemented"
            evidence: "Encryption configurations"
