apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-verify
  namespace: secureai
spec:
  schedule: "30 */6 * * *"  # 30 minutes after each backup
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: verify
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              LATEST_BACKUP=$(ls -t /backups/*.gz | head -1)
              if [ -z "$LATEST_BACKUP" ]; then
                echo "No backup found"
                exit 1
              fi

              gunzip -c $LATEST_BACKUP | pg_restore --list > /dev/null
              if [ $? -eq 0 ]; then
                echo "Backup verification successful"
              else
                echo "Backup verification failed"
                exit 1
              fi
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
              readOnly: true
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: db-backup-pvc
          restartPolicy: OnFailure
