apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- network-policy.yaml
- pod-security-policy.yaml
- monitoring/prometheus-servicemonitor.yaml
- monitoring/prometheus-rules.yaml
- hpa.yaml
- pdb.yaml
- backup/velero-backup.yaml
- backup/storage-location.yaml
- backup/backup-verify.yaml
- dr/failover-config.yaml
- dr/dr-test.yaml
- dr/geo-replication.yaml
- monitoring/backup-monitor.yaml
- monitoring/dr-monitor.yaml
- monitoring/grafana-dashboard.yaml
- monitoring/backup-metrics.yaml
- monitoring/alert-manager.yaml
- monitoring/alert-templates.yaml
- dr/test-scenarios.yaml
- dr/test-executor.yaml
- dr/test-rbac.yaml
- backup/validation-tests.yaml
- backup/validation-config.yaml
- backup/validation-service.yaml
- monitoring/alert-channels.yaml
- backup/extended-validation-tests.yaml
- monitoring/extended-alert-templates.yaml
- monitoring/backup-validation-metrics.yaml
- monitoring/backup-validation-dashboard.yaml
- monitoring/custom-dashboards.yaml
- monitoring/dashboard-config.yaml
- monitoring/dashboard-updater.yaml
- dr/dr-test-suite.yaml
- dr/dr-test-executor.yaml
- dr/dr-test-monitoring.yaml
- dr/dr-test-reporter.yaml
- compliance/documentation-config.yaml
- compliance/documentation-generator.yaml
- compliance/evidence-collector.yaml
- compliance/compliance-monitor.yaml

commonLabels:
  app: secureai-platform

namespace: secureai
