apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureai-staging

bases:
- ../../base

patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml

resources:
- namespace.yaml

commonLabels:
  environment: staging
